# Generated by Django 5.2.1 on 2025-06-17 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NewsletterSignup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("genres", models.CharField(blank=True, max_length=500)),
                ("date_joined", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
