# Generated by Django 5.2.1 on 2025-06-17 18:27

from django.db import migrations, models
import uuid


def populate_tokens(apps, schema_editor):
    NewsletterSignup = apps.get_model('newsletter', 'NewsletterSignup')
    for signup in NewsletterSignup.objects.filter(
        unsubscribe_token__isnull=True
    ):
        signup.unsubscribe_token = uuid.uuid4()
        signup.save()


class Migration(migrations.Migration):

    dependencies = [
        ("newsletter", "0002_newslettersignup_unsubscribe_token"),
    ]

    operations = [
        migrations.RunPython(populate_tokens),
    ]
