# Generated by Django 5.2.1 on 2025-06-17 18:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsletter", "0003_populate_unsubscribe_tokens"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newslettersignup",
            name="unsubscribe_token",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
