# Generated by Django 5.2.1 on 2025-06-27 17:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsletter", "0005_alter_newslettersignup_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="newslettersignup",
            options={
                "ordering": ["-date_joined"],
                "verbose_name": "Subscriber",
                "verbose_name_plural": "Subscribers",
            },
        ),
        migrations.AlterField(
            model_name="newslettersignup",
            name="date_joined",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Timestamp when the subscription was created",
            ),
        ),
        migrations.AlterField(
            model_name="newslettersignup",
            name="email",
            field=models.EmailField(
                help_text="Subscriber's email address", max_length=254, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="newslettersignup",
            name="genres",
            field=models.CharField(
                blank=True,
                help_text="Comma-separated list of preferred genres",
                max_length=500,
            ),
        ),
        migrations.AlterField(
            model_name="newslettersignup",
            name="unsubscribe_token",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                help_text="Token used to securely unsubscribe via email link",
                unique=True,
            ),
        ),
    ]
