# Generated by Django 5.2.1 on 2025-05-19 12:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactus",
            name="email",
            field=models.EmailField(
                max_length=254, validators=[django.core.validators.EmailValidator()]
            ),
        ),
        migrations.AlterField(
            model_name="contactus",
            name="first_name",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="contactus",
            name="last_name",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="contactus",
            name="message",
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
