# Generated by Django 5.2.1 on 2025-05-19 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0002_alter_contactus_email_alter_contactus_first_name_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contactus",
            options={"verbose_name_plural": "Contact Us"},
        ),
    ]
