# Generated by Django 5.2.1 on 2025-05-19 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0003_alter_contactus_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contactus",
            options={"verbose_name_plural": "Messages"},
        ),
    ]
