# Generated by Django 5.2.1 on 2025-05-19 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0004_alter_contactus_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contactus",
            options={"verbose_name": "Message", "verbose_name_plural": "Messages"},
        ),
    ]
