# Generated by Django 5.2.1 on 2025-05-28 10:18

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0005_alter_contactus_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactus",
            name="message",
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, max_length=1000),
        ),
    ]
