# Generated by Django 5.2.1 on 2025-06-16 19:18

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0006_alter_contactus_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactus",
            name="message",
            field=django_ckeditor_5.fields.CKEditor5Field(max_length=1000),
        ),
    ]
