# Generated by Django 5.2.1 on 2025-06-27 17:07

import django.core.validators
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0007_alter_contactus_message"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contactus",
            options={
                "ordering": ["-created"],
                "verbose_name": "Message",
                "verbose_name_plural": "Messages",
            },
        ),
        migrations.AlterField(
            model_name="contactus",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Timestamp when the message was created"
            ),
        ),
        migrations.AlterField(
            model_name="contactus",
            name="email",
            field=models.EmailField(
                help_text="Email address of the sender",
                max_length=254,
                validators=[django.core.validators.EmailValidator()],
            ),
        ),
        migrations.AlterField(
            model_name="contactus",
            name="first_name",
            field=models.CharField(help_text="First name of the sender", max_length=50),
        ),
        migrations.AlterField(
            model_name="contactus",
            name="last_name",
            field=models.CharField(help_text="Last name of the sender", max_length=50),
        ),
        migrations.AlterField(
            model_name="contactus",
            name="message",
            field=django_ckeditor_5.fields.CKEditor5Field(
                help_text="Message content", max_length=1000
            ),
        ),
    ]
