# Generated by Django 5.2.1 on 2025-05-19 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("releases", "0002_alter_images_caption_alter_images_title_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="images",
            options={"verbose_name_plural": "Images"},
        ),
        migrations.AlterModelOptions(
            name="rating",
            options={"verbose_name_plural": "Ratings"},
        ),
        migrations.AlterModelOptions(
            name="releases",
            options={"verbose_name_plural": "Releases"},
        ),
    ]
