# Generated by Django 5.2.1 on 2025-05-19 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("releases", "0003_alter_images_options_alter_rating_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="images",
            name="is_featured",
            field=models.BooleanField(default=False, verbose_name="Featured Image"),
        ),
        migrations.RemoveField(
            model_name="releases",
            name="image",
        ),
        migrations.AddField(
            model_name="releases",
            name="image",
            field=models.ManyToManyField(
                blank=True, related_name="releases", to="releases.images"
            ),
        ),
    ]
