# Generated by Django 5.2.1 on 2025-05-19 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("releases", "0004_alter_images_is_featured_remove_releases_image_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="images",
            options={"verbose_name": "Image", "verbose_name_plural": "Images"},
        ),
        migrations.AlterModelOptions(
            name="rating",
            options={"verbose_name": "Rating", "verbose_name_plural": "Ratings"},
        ),
        migrations.AlterModelOptions(
            name="releases",
            options={"verbose_name": "Release", "verbose_name_plural": "Releases"},
        ),
    ]
