# Generated by Django 5.2.1 on 2025-05-24 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("releases", "0005_alter_images_options_alter_rating_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="releases",
            name="director",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
