# Generated by Django 5.2.1 on 2025-05-24 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("releases", "0006_releases_director"),
    ]

    operations = [
        migrations.AlterField(
            model_name="releases",
            name="censor_status",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="releases",
            name="packaging",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
