# Generated by Django 5.2.1 on 2025-05-25 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("releases", "0007_alter_releases_censor_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="releases",
            name="price",
            field=models.DecimalField(decimal_places=2, default=19.99, max_digits=10),
            preserve_default=False,
        ),
    ]
