# Generated by Django 5.2.1 on 2025-05-26 12:32

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("releases", "0011_alter_rating_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="images",
            name="image",
            field=cloudinary.models.CloudinaryField(
                blank=True,
                default="holding_image",
                max_length=255,
                verbose_name="image",
            ),
        ),
    ]
