# Generated by Django 5.2.1 on 2025-05-28 09:39

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ("releases", "0012_alter_images_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rating",
            name="review",
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, max_length=1500, null=True),
        ),
        migrations.AlterField(
            model_name="releases",
            name="description",
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="releases",
            name="special_features",
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, max_length=2000, null=True),
        ),
    ]
