# Generated by Django 5.2.1 on 2025-06-09 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("releases", "0013_alter_rating_review_alter_releases_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="releases",
            name="copies_available",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
