# Generated by Django 5.2.1 on 2025-06-09 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("releases", "0014_alter_releases_copies_available"),
    ]

    operations = [
        migrations.AlterField(
            model_name="releases",
            name="copies_available",
            field=models.IntegerField(default=0),
        ),
    ]
