# Generated by Django 5.2.1 on 2025-06-27 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("releases", "0015_alter_releases_copies_available"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="images",
            options={
                "ordering": ["-is_featured", "date_added"],
                "verbose_name": "Image",
                "verbose_name_plural": "Images",
            },
        ),
        migrations.AlterModelOptions(
            name="releases",
            options={
                "ordering": ["title"],
                "verbose_name": "Release",
                "verbose_name_plural": "Releases",
            },
        ),
        migrations.RemoveField(
            model_name="releases",
            name="image",
        ),
    ]
