# Generated by Django 5.2.1 on 2025-06-27 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("releases", "0016_alter_images_options_alter_releases_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="releases",
            name="images",
            field=models.ManyToManyField(
                blank=True,
                help_text="Related images for this release",
                related_name="releases",
                to="releases.images",
            ),
        ),
        migrations.AlterField(
            model_name="images",
            name="title",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="image",
                to="releases.releases",
            ),
        ),
    ]
