# Generated by Django 5.2.1 on 2025-06-27 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("releases", "0017_releases_images_alter_images_title"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="releases",
            name="images",
        ),
    ]
