# Generated by Django 5.2.1 on 2025-06-27 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("releases", "0018_remove_releases_images"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="images",
            options={"verbose_name": "Image", "verbose_name_plural": "Images"},
        ),
        migrations.AlterModelOptions(
            name="releases",
            options={"verbose_name": "Release", "verbose_name_plural": "Releases"},
        ),
        migrations.AddField(
            model_name="releases",
            name="image",
            field=models.ManyToManyField(
                blank=True, related_name="releases", to="releases.images"
            ),
        ),
        migrations.AlterField(
            model_name="images",
            name="title",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="releases.releases",
            ),
        ),
    ]
