# Generated by Django 5.2.1 on 2025-06-27 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("releases", "0019_alter_images_options_alter_releases_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="releases",
            name="image",
        ),
    ]
