# Generated by Django 5.2.6 on 2026-08-12 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('releases', '0021_alter_releases_copies_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(blank=True, default='site/holding_image', upload_to='releases/'),
        ),
    ]
