# Generated by Django 5.2.1 on 2025-06-07 07:14

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0002_order_original_bag_order_stripe_pid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="country",
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
