# Generated by Django 5.2.1 on 2025-06-07 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0003_alter_order_country"),
        (
            "the_cult_film_club_account",
            "0004_address_phone_number_alter_address_city_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="user_profile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="the_cult_film_club_account.profile",
            ),
        ),
    ]
