# Generated by Django 5.2.1 on 2025-06-10 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0005_order_discount"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="discount_code",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
