# Generated by Django 5.2.1 on 2025-06-12 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0006_order_discount_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="stripe_pid",
            field=models.CharField(default="", max_length=254, unique=True),
        ),
    ]
