# Generated by Django 5.2.1 on 2025-06-14 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0007_alter_order_stripe_pid"),
    ]

    operations = [
        migrations.CreateModel(
            name="DiscountCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=50, unique=True)),
                (
                    "percent",
                    models.PositiveIntegerField(
                        help_text="Discount percent (For example, 10 for 10%)"
                    ),
                ),
                ("valid_from", models.DateField(help_text="Start date (DD-MM-YYYY)")),
                ("valid_to", models.DateField(help_text="End date (DD-MM-YYYY)")),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
    ]
