# Generated by Django 5.2.1 on 2025-06-15 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0008_discountcode"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="loyalty_points_discount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
