# Generated by Django 5.2.1 on 2025-06-15 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0009_order_loyalty_points_discount"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="loyalty_points_used",
            field=models.IntegerField(default=0),
        ),
    ]
