# Generated by Django 5.2.1 on 2025-06-15 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0010_order_loyalty_points_used"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="loyalty_points_discount",
        ),
        migrations.RemoveField(
            model_name="order",
            name="loyalty_points_used",
        ),
    ]
