# Generated by Django 5.2.1 on 2025-06-26 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0011_remove_order_loyalty_points_discount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="delivery_method",
            field=models.CharField(
                blank=True,
                help_text="e.g., 'standard', 'next_day'",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_override",
            field=models.BooleanField(
                default=False, help_text="If True, skip auto-calculating delivery_cost"
            ),
        ),
        migrations.AlterField(
            model_name="discountcode",
            name="percent",
            field=models.PositiveIntegerField(
                help_text="Discount percent (e.g., 10 for 10%)"
            ),
        ),
    ]
