# Generated by Django 5.2.1 on 2025-06-26 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0012_order_delivery_method_order_delivery_override_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="delivery_method",
        ),
        migrations.RemoveField(
            model_name="order",
            name="delivery_override",
        ),
        migrations.AlterField(
            model_name="discountcode",
            name="percent",
            field=models.PositiveIntegerField(
                help_text="Discount percent (For example, 10 for 10%)"
            ),
        ),
    ]
