# Generated by Django 5.2.1 on 2025-06-27 16:29

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0013_remove_order_delivery_method_and_more"),
        ("the_cult_film_club_account", "0011_alter_wishlistitem_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discountcode",
            name="percent",
            field=models.PositiveIntegerField(
                help_text="Discount percent (e.g., 10 for 10%)"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="discount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Discount amount subtracted from total",
                max_digits=6,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="discount_code",
            field=models.CharField(
                blank=True,
                help_text="Code for applied discount (if any)",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_number",
            field=models.CharField(
                editable=False,
                help_text="Unique order identifier",
                max_length=32,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="stripe_pid",
            field=models.CharField(
                default="",
                help_text="Stripe Payment Intent ID",
                max_length=254,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="user_profile",
            field=models.ForeignKey(
                blank=True,
                help_text="Profile of user who placed the order (optional)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="the_cult_film_club_account.profile",
            ),
        ),
        migrations.AlterField(
            model_name="orderlineitem",
            name="lineitem_total",
            field=models.DecimalField(
                decimal_places=2,
                editable=False,
                help_text="Total price for this line item (price * quantity)",
                max_digits=6,
            ),
        ),
        migrations.AlterField(
            model_name="orderlineitem",
            name="quantity",
            field=models.PositiveIntegerField(
                default=1, help_text="Quantity of this release in the order"
            ),
        ),
    ]
