# Generated by Django 5.2.1 on 2025-06-27 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0014_alter_discountcode_percent_alter_order_discount_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discountcode",
            name="percent",
            field=models.PositiveIntegerField(
                help_text="Discount percent (For example, 10 for 10%)"
            ),
        ),
    ]
