# Generated by Django 5.2.1 on 2025-07-01 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0015_alter_discountcode_percent"),
        ("the_cult_film_club_account", "0012_remove_profile_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="user_profile",
            field=models.ForeignKey(
                blank=True,
                help_text="Profile of user who placed the order (optional)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="the_cult_film_club_account.profile",
            ),
        ),
    ]
