# Generated by Django 5.2.1 on 2025-05-26 11:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("releases", "0011_alter_rating_unique_together"),
        ("the_cult_film_club_account", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="wishlist",
            constraint=models.UniqueConstraint(
                fields=("user",), name="unique_user_wishlist"
            ),
        ),
    ]
