# Generated by Django 5.2.1 on 2025-05-28 10:18

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("the_cult_film_club_account", "0002_wishlist_unique_user_wishlist"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wishlistitem",
            name="notes",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True, max_length=1000, null=True
            ),
        ),
    ]
