# Generated by Django 5.2.1 on 2025-05-19 11:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_alter_profile_address"),
        ("releases", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="second_line",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="address",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="address",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RemoveField(
            model_name="profile",
            name="address",
        ),
        migrations.AlterField(
            model_name="wishlist",
            name="notes",
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.RemoveField(
            model_name="wishlist",
            name="title",
        ),
        migrations.AlterField(
            model_name="wishlist",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="wishlists",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="address",
            field=models.ManyToManyField(related_name="profile", to="account.address"),
        ),
        migrations.AddField(
            model_name="wishlist",
            name="title",
            field=models.ManyToManyField(
                related_name="wishlists", to="releases.releases"
            ),
        ),
    ]
