# Generated by Django 5.2.1 on 2025-05-19 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_alter_address_second_line_alter_address_user_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="address",
            options={"verbose_name_plural": "Addresses"},
        ),
        migrations.AlterModelOptions(
            name="profile",
            options={"verbose_name_plural": "Profiles"},
        ),
        migrations.AlterModelOptions(
            name="wishlist",
            options={"verbose_name_plural": "Wishlists"},
        ),
    ]
