# Generated by Django 5.2.1 on 2025-06-07 13:48

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "the_cult_film_club_account",
            "0004_address_phone_number_alter_address_city_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="country",
            field=django_countries.fields.CountryField(
                default="GB", max_length=2
            ),
            preserve_default=False,
        ),
    ]
