# Generated by Django 5.2.1 on 2025-05-19 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0004_alter_address_options_alter_profile_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wishlist",
            name="is_purchased",
            field=models.BooleanField(default=False, verbose_name="Purchased"),
        ),
    ]
