# Generated by Django 5.2.1 on 2025-05-19 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0005_alter_wishlist_is_purchased"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="address",
            options={"verbose_name": "Address", "verbose_name_plural": "Addresses"},
        ),
        migrations.AlterModelOptions(
            name="profile",
            options={"verbose_name": "Profile", "verbose_name_plural": "Profiles"},
        ),
        migrations.AlterModelOptions(
            name="wishlist",
            options={"verbose_name": "Wishlist", "verbose_name_plural": "Wishlists"},
        ),
    ]
