# Generated by Django 5.2.1 on 2025-06-09 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("the_cult_film_club_account", "0005_alter_address_country"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="default_address",
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
