# Generated by Django 5.2.1 on 2025-06-14 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("the_cult_film_club_account", "0006_alter_address_default_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="city",
            field=models.CharField(default="City", max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="address",
            name="first_line",
            field=models.CharField(default="First Line", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="address",
            name="postcode",
            field=models.CharField(default="Postcode", max_length=10),
            preserve_default=False,
        ),
    ]
