# Generated by Django 5.2.1 on 2025-06-14 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "the_cult_film_club_account",
            "0007_alter_address_city_alter_address_first_line_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="label",
            field=models.CharField(
                blank=True, help_text="For example, 'Home' or 'Work'", max_length=15
            ),
        ),
    ]
