# Generated by Django 5.2.1 on 2025-06-14 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("the_cult_film_club_account", "0008_address_label"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="label",
            field=models.CharField(
                help_text="For example, 'Home' or 'Work'", max_length=15
            ),
        ),
    ]
