# Generated by Django 5.2.1 on 2025-06-23 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("the_cult_film_club_account", "0009_alter_address_label"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="loyalty_points",
        ),
    ]
