# Generated by Django 5.2.1 on 2025-06-27 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("the_cult_film_club_account", "0010_remove_profile_loyalty_points"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="wishlistitem",
            options={
                "verbose_name": "Wishlist Item",
                "verbose_name_plural": "Wishlist Items",
            },
        ),
    ]
