# Generated by Django 5.2.1 on 2025-06-28 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("the_cult_film_club_account", "0011_alter_wishlistitem_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="address",
        ),
    ]
