# Generated by Django 5.2.1 on 2025-07-01 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "the_cult_film_club_account",
            "0013_remove_wishlist_unique_user_wishlist_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="wishlistitem",
            name="is_purchased",
        ),
    ]
