# Generated by Django 5.2.6 on 2026-08-12 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_cult_film_club_account', '0014_remove_wishlistitem_is_purchased'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photograph',
            field=models.ImageField(blank=True, default='site/placeholder', upload_to='profiles/'),
        ),
    ]
